# Fichier Makefile

CC = gcc
CFLAGS = -g -Wall -ansi -D _GNU_SOURCE 
CFLAG2 = -c -Wall -ansi -D _GNU_SOURCE 

all: cl CL

cl : CL_main.c
	$(CC) $(CFLAGS) CL_main.c -o CL

clean:
	@rm -f *~ *.o sv_zz SV 





